### ISSUE TITLE
a tips

### ISSUE THREAD

**Issue by linflytang** [DevJx3D/FullSource#1]
this version have missing a lot files. Maybe you can start from a more full version（剑侠情缘单机本叁 - Dev by JSON-GAME）. You can find it in network.

**Comment by HadesD** [comment]
@linflytang thanks you so much for that huge hint.

I 'll find it and update this project tho.

**Comment by HadesD** [comment]
@linflytang I 've tried to find '剑侠情缘单机本叁 - Dev by JSON-GAME' in google/bing/baidu and some china 's website/forum, but no more infomation about it, so sad.

I 've found a site named 'seasungame' that shared a version of this game, but I can't read chinese, so difficult to find it.

It is so happy if you can give me a website that talking/sharing the source code?

Thanks
